print("stop right there!")
import time
import os
time.sleep(1.5)
os.system('clear')
time.sleep(0.2)
name = input("what is your name?_")
os.system('clear')
time.sleep(1)
print("ok then...")
time.sleep(1)
print(name + "...")
time.sleep(2)
print("that name is kinda sus...")
time.sleep(3)
os.system('clear')
time.sleep(0)
print("just say >>>yes<<<")
time.sleep(0.5)
nothing = input("would you like to do my challenge??_")
if nothing == 'yes':
  os.system('clear')
  time.sleep(0.5)
  print("ok fine!")
if nothing == 'no':
  os.system('clear')
  print("how rude...")
  time.sleep(1)
  os.system('clear')
  time.sleep(0.2)
  while(True):
    print("go away")
    time.sleep(0.5)
time.sleep(1)
os.system('clear')
number = input("think of a number_")
os.system('clear')
time.sleep(0.5)
print("now remember that number")
time.sleep(1)
print("dont forget it!")
time.sleep(2)
os.system('clear')
print("im going to ask you some questions...")
time.sleep(3)
os.system('clear')
pickles = input("do you like pickels?_")
if pickles == 'no':
  os.system('clear')
  whyp = input("why dont you like pickels??_")
  print("understandable...")
if pickles == 'yes':
  print("i love you...")
time.sleep(2)
os.system('clear')
print("do you like women??_")
time.sleep(2)
os.system('clear')
print("oh")
time.sleep(1)
os.system('clear')
print("wrong question...")
time.sleep(1.5)
os.system('clear')
screen = input("are you looking at your sreen?_")
if screen == ('no'):
  os.system('clear')
  print("im not stupid")
  time.sleep(1)
  print("you are lying")
if screen == ('yes'):
  os.system('clear')
  print("correct!")
  time.sleep(1)
  print("thank you for not lying")
time.sleep(3)
os.system('clear')
redy = input("are you ready for my incredible prediction??_")
if redy == ('yes'):
  os.system('clear')
  print("one sec...")
  time.sleep(2)
if redy == ('no'):
  os.system('clear')
  print("i dont care")
  time.sleep(1)
os.system('clear')
print("according to my calculations...")
time.sleep(3)
os.system('clear')
print("You, Sir." + name)
time.sleep(2)
os.system('clear')
print("You were thinking of the number", number)
time.sleep(3)
while(True):
  print("skills")
  time.sleep(0.5)